# Default values for guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --------------------------------------------
registryHost: hub.yuansuan.cn
imageTagPrefix: hub.yuansuan.cn/yy
# --------------------------------------------

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
